CREATE TABLE [Table]
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Number INT NOT NULL,
	Available BIT NOT NULL
)
CREATE NONCLUSTERED INDEX [IX_Table_Number] ON [dbo].[Table]
(
	[Number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Table_Available] ON [dbo].[Table]
(
	[Available] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Table] ADD  CONSTRAINT [DF_Table_Available]  DEFAULT ((1)) FOR Available
GO