CREATE TABLE Bill
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	TableId INT FOREIGN KEY REFERENCES [Table](Id),
	[Status] VARCHAR(15) NOT NULL,
	Value MONEY NOT NULL
)
CREATE NONCLUSTERED INDEX [IX_Bill_TableId] ON [dbo].[Bill]
(
	[TableId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO