CREATE TABLE OrderItems
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	OrderId INT FOREIGN KEY REFERENCES [Order](Id),
	ItemId INT FOREIGN KEY REFERENCES Item(Id),
	Quantity INT NOT NULL,
	UnitValue MONEY NOT NULL,
	TotalValue MONEY NOT NULL,
	Comments VARCHAR(200)
)